name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
    pull_request:
      branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - run: dotnet restore

      - run: dotnet build --no-restore

      - run: dotnet test --no-build

      # docker
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/docker-api:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.actor }}/docker-api:latest
